import numpy as np
import pandas as pd
import networkx as nx
from networkx.algorithms.community import greedy_modularity_communities, modularity
import igraph as ig
import math
import json


# =========== Load raw data ===========
def _adj_mx_gnw_goldstandard(filepath: str) -> np.ndarray:
    """
    Convert a GeneNetWeaver edge list to an adjacency matrix.

    Parameters
    ----------
    filepath : str
        Path to the edge list (.tsv file) generated by GeneNetWeaver.
        The file must have three columns: source, target, and interaction.

    Returns
    -------
    np.ndarray
        A binary adjacency matrix as a NumPy array (shape: [n_nodes, n_nodes]),
        where 1 indicates an interaction and 0 indicates no interaction.
    """
    df = pd.read_csv(filepath, sep="\t", header=None, names=["source", "target", "interaction"])
    active_edges = df[df["interaction"] == 1]
    G = nx.from_pandas_edgelist(active_edges, source="source", target="target", create_using=nx.DiGraph())
    return nx.adjacency_matrix(G).toarray()

def _remove_nan_values(species: list) -> None:
    """
    Removes NaN values from the end of the gene and interaction lists of
    a species.

        Args:
            - species (list): A list containing two lists:
            [gene_list, interaction_list]
    """
    # Check if the last element is not a string (i.e., it's NaN)
    while type(species[0][-1]) is not str:
        species[0].pop()  # Remove the last gene entry
        species[1].pop()  # Remove the corresponding interaction entry

# =========== Preprocess raw data ===========
def _create_graph(species: list) -> nx.DiGraph:
    """
    Creates a directed graph from gene interactions for a given species.

        Args:
            - species (list): A list containing two lists:
            [gene_list, interaction_list]

        Returns:
            nx.DiGraph: A directed graph representing gene interactions.
    """
    N = len(species[0])  # Number of gene interactions
    Graph = nx.DiGraph()  # Create an empty directed graph
    for i in range(N):
        Graph.add_edge(species[0][i], species[1][i])  # Add edges to the graph
    return Graph

def get_largest_cc(graph: nx.DiGraph):
    weakly_connected_nodeset = max(nx.weakly_connected_components(graph), key=len)
    largest_cc = graph.subgraph(weakly_connected_nodeset).copy()
    return largest_cc

def edgelist_to_graph(network: str, verbose=False):
    '''
    Load edge list file to dataframe and return the graph as networkx.DiGraph()
    Input:
        network: must be a network name within 
        ['GSD', 'HSC', 'mCAD', 'VSC', 
        'hESC', 'mDC', 'mESC', 'yeast', 
        'ecoli_gnw', 
        'human_trrust', 
        "athaliana_wolf", "dmelanogaster_wolf", "ecoli_wolf", "hsapiens_wolf", "scerevisiae_wolf"]
    Output:
        graph: nx.DiGraph()
    '''
    
    if network not in ['GSD', 'HSC', 'mCAD', 'VSC', 
        'hESC', 'mDC', 'mESC', 'yeast', 
        'ecoli_gnw', 
        'human_trrust', 
        "athaliana_wolf", "dmelanogaster_wolf", "ecoli_wolf", "hsapiens_wolf", "scerevisiae_wolf"]:
        print(f"{network} not supported. Please consult the documentation for supported datasets.")
    
    if network in ['GSD', 'HSC', 'mCAD', 'VSC']:
        edge_df=pd.read_csv(f"../../data/raw/beeline/beeline_datasets/Curated/{network}/{network}-2000-1/refNetwork.csv")
        graph_full = nx.from_pandas_edgelist(
            edge_df,
            source="Gene1",
            target="Gene2",
            edge_attr="Type",
            create_using=nx.DiGraph()
        )
        
    if network in ['hESC', 'mDC', 'mESC', 'yeast']:
        edge_df=pd.read_csv(f"../../data/raw/mccalla/{network}/{network}_chipunion_KDUnion_intersect.txt", delimiter='\t', header=None)
        graph_full = nx.from_pandas_edgelist(
                                            edge_df,
                                            source=0,
                                            target=1,
                                            create_using=nx.DiGraph()
                                        )
        
    if network == 'ecoli_gnw':
        adj_mx = _adj_mx_gnw_goldstandard('../../data/raw/gnw/Ecoli-full.tsv')
        graph_full = nx.from_numpy_array(adj_mx, create_using=nx.DiGraph())
        
    if network == 'human_trrust':
        filepath = "../../data/raw/trrust/trrust_rawdata.human.tsv"
        df_hsapiens_raw = pd.read_csv(filepath,sep='\t',
                                      header=None,
                                      names=['TF','Target','Edge Type','Unknown'])
        df_hsapiens = df_hsapiens_raw[df_hsapiens_raw['Edge Type'] != 'Unknown']
        graph_full = nx.from_pandas_edgelist(df_hsapiens, 
                                           source='TF', 
                                           target='Target', 
                                           create_using=nx.DiGraph(), 
                                           edge_attr=True)
        
    if network in ["athaliana_wolf", "dmelanogaster_wolf", "ecoli_wolf", "hsapiens_wolf", "scerevisiae_wolf"]:
        filepath = "../../data/raw/wolf/41598_2021_3625_MOESM5_ESM.xlsx"
        file = pd.read_excel(filepath)
        if network == "athaliana_wolf":
            table = (file["""Supplementary Table S1: Networks. A spreadsheet file with filtered networks"""].tolist()[2:],
                     file["Unnamed: 1"].tolist()[2:],
                     "Arabidopsis thaliana")
        if network == "dmelanogaster_wolf":
            table = (file["Unnamed: 2"].tolist()[2:], 
                     file["Unnamed: 3"].tolist()[2:], 
                     "Drosophila Melanogaster")
        if network == "ecoli_wolf":
            table = (file["Unnamed: 4"].tolist()[2:],
                     file["Unnamed: 5"].tolist()[2:],
                     "Escherichnia coli")
        if network == "hsapiens_wolf":
            table = (file["Unnamed: 6"].tolist()[2:], 
                     file["Unnamed: 7"].tolist()[2:],
                     "Homo sapiens")
        if network == "scerevisiae_wolf":
            table =(file["Unnamed: 8"].tolist()[2:],
                    file["Unnamed: 9"].tolist()[2:],
                    "Saccharomyces cerevisiae")

        _remove_nan_values(table)
        graph_full = _create_graph(table)
        
    if not nx.is_weakly_connected(graph_full):
        graph = get_largest_cc(graph_full)
        if verbose:
            print(f"{network} network is not weakly connected.")
            print(f"Only the largest weakly connected component has been loaded:")
            print(f"Original network has {graph_full.number_of_nodes()} nodes and {graph_full.number_of_edges()} edges.")
            print(f"Largest weakly connected component has {graph.number_of_nodes()} nodes and {graph.number_of_edges()} edges.")
    else:
        graph=graph_full
        
    return graph

# =========== Compute properties ===========
def get_degrees_original(G):
    in_degree = [d for n, d in G.in_degree()]
    out_degree = [d for n, d in G.out_degree()]
    return in_degree, out_degree

def get_degree_pairs(G):
    out_deg = dict(G.out_degree())
    in_deg = dict(G.in_degree())
    out_out = [(out_deg[u], out_deg[v]) for u, v in G.edges()]
    out_in = [(out_deg[u], in_deg[v]) for u, v in G.edges()]
    in_out = [(in_deg[u], out_deg[v]) for u, v in G.edges()]
    in_in = [(in_deg[u], in_deg[v]) for u, v in G.edges()]
    return out_out, out_in, in_out, in_in

def compute_modularity(G):
    """
    G : nx.Graph
        An undirected graph (NetworkX DiGraph).
    """
    communities = greedy_modularity_communities(G.to_undirected())
    modularity_value = modularity(G, communities)
    return modularity_value

def average_path_length_directed(G):
    """Compute the average shortest path length among reachable node pairs (Gephi-style)."""
    if not G.is_directed():
        return nx.average_shortest_path_length(G)
    
    total_length = 0
    count = 0
    
    for node in G.nodes():
        # Get shortest paths from this node to all reachable others
        lengths = nx.single_source_shortest_path_length(G, node)
        # Exclude self (distance 0)
        total_length += sum(length for target, length in lengths.items() if target != node)
        count += len(lengths) - 1  # exclude self
    
    return total_length / count if count > 0 else float('nan')


def directed_path_stats(G):
    if not isinstance(G, nx.DiGraph):
        raise TypeError("Expected a directed graph")

    all_lengths = 0
    count = 0
    diameter = 0

    for node in G.nodes():
        neighbour_distance = nx.single_source_shortest_path_length(G, node)
        for target, distance in neighbour_distance.items():
            if target != node:
                all_lengths += distance
                count += 1
                if distance > diameter:
                    diameter = distance

    avg_length = all_lengths / count
    diameter = diameter

    return avg_length, diameter

def compute_network_properties(G, save_path=None):
    """
    Compute properties of a directed network.

    Parameters
    ----------
    G : nx.DiGraph
        A directed graph (NetworkX DiGraph).

    save_json_path : str or None, optional
        If provided, saves the computed results as a JSON file at this path.

    Returns
    -------
    dict
        A dictionary containing various network statistics.
    """
    res = {}
    uG = G.to_undirected()
    
    # Degree distribution
    degree_sequence = sorted((d for n, d in G.degree()), reverse=True)
    N = G.number_of_nodes()
    degree_counts = np.unique(degree_sequence, return_counts=True)
    degrees = degree_counts[0]
    counts = degree_counts[1]
    degree_probabilities = counts / N
    
    # Directed path stats
    avg_length_dir, diameter_dir = directed_path_stats(G)

    res['assortiativity_out_in'] = round(nx.degree_pearson_correlation_coefficient(G, x='out', y='in'), 4)
    res['assortiativity_out_out'] = round(nx.degree_pearson_correlation_coefficient(G, x='out', y='out'), 4)
    res['assortiativity_in_in'] = round(nx.degree_pearson_correlation_coefficient(G, x='in', y='in'), 4)
    res['assortiativity_in_out'] = round(nx.degree_pearson_correlation_coefficient(G, x='in', y='out'), 4)
    res['avg_clustering_dir'] = round(nx.average_clustering(G), 4)
    res['avg_clustering_undir'] = round(nx.average_clustering(uG), 4)
    res['avg_degree'] = round(sum(dict(G.degree()).values()) / N, 4)
    res['avg_path_dir'] = round(avg_length_dir, 4)
    res['avg_path_undir'] = round(nx.average_shortest_path_length(uG), 4)
    # res['degrees'] = degrees
    # res['degree_counts'] = counts
    res['density'] = round(nx.density(G), 7)
    # res['degree_proba'] = degree_probabilities
    res['diameter'] = diameter_dir
    res['diameter_undir'] = nx.diameter(uG)
    # res['modularity'] = round(compute_modularity(uG), 4)
    res['nb_edges'] = G.number_of_edges()
    res['nb_nodes'] = N
    # res['strongly_connected'] = nx.is_strongly_connected(G)
    # res['weakly_connected'] = nx.is_weakly_connected(G)

    # --- Optional: Save as JSON ---
    if save_path is not None:
        result2save = {
            k: (v.tolist() if isinstance(v, np.ndarray) else v)
            for k, v in res.items()
        }
        with open(save_path, "w") as f:
            json.dump(result2save, f, indent=2)
        print(f"Network statistics saved to '{save_path}'")

    return res

def nx_to_igraph(Gnx):
    nodes = list(Gnx.nodes())
    node_index = {n: i for i, n in enumerate(nodes)}
    edges = [(node_index[u], node_index[v]) for u, v in Gnx.edges()]
    G = ig.Graph(directed=True)
    G.add_vertices(len(nodes))
    G.add_edges(edges)
    return G, node_index

def count_motifs(G, save_path=None, nx_graph=True):

    motif_names=[None,
     None,
     'Fan-In',
     None,
     'Cascade',
     'Mutual-In',
     'Fan-Out',
     'FFL',
     'Regulated-Mutual',
     'Mutual-Out',
     'Bi-Mutual',
     'FBL',
     'Mutual-Cascade',
     'Regulating-Mutual',
     'Semi-Clique',
     'Clique']
    
    if nx_graph:
        Gnx = G
        G_ig, _ = nx_to_igraph(Gnx)
    else:
        G_ig = G
    motif_counts = G_ig.motifs_randesu(size=3)  # list of length 1
    motif_counts_dict={}
    motif_counts_dict = {
        motif: motif_counts[i]
        for i, motif in enumerate(motif_names)
        if motif
    }
    motif_counts_dict_sorted = dict(sorted(motif_counts_dict.items()))
    
    if save_path:
        with open(save_path, "w") as f:
            json.dump(motif_counts_dict_sorted, f, indent=2)
        print(f"Motif counts saved to '{save_path}'")

    return motif_counts_dict_sorted

def harmonize_stats(ground_truth_stat, df_stats, save_path=None):

    keys_to_remove = {
        "degrees",
        "degree_counts",
        "degree_proba",
        "strongly_connected",
        "weakly_connected",
        "nb_nodes",
        "avg_degree",
        "modularity",
        "density",
        "nb_edges",
        'avg_clustering_undir', 
        'avg_path_undir', 
        'diameter_undir'
    }

    ground_truth_clean = {
        k: v for k, v in sorted(ground_truth_stat.items())
        if k not in keys_to_remove
    }

    cols_to_drop = ["avg_degree", "nb_nodes", "density", "energies"]
    cols_to_drop = [col for col in cols_to_drop if col in df_stats.columns]
    df_clean = df_stats.drop(columns=cols_to_drop)

    # Compute energies using only keys present in both
    gt_keys = set(ground_truth_clean.keys())
    
    df_clean["energies"] = df_clean.apply(
        lambda row: energy_delta(
            {k: row[k] for k in gt_keys if k in row.index},
            ground_truth_clean
        ),
        axis=1,
    )

    if save_path:
        df_clean.to_csv(save_path, index=False)

    return df_clean, ground_truth_clean

# =========== Load prepocess data ===========
def load_graphs(folderpath=None):
    if folderpath:
        ground_truth_graph = nx.read_graphml(f"{folderpath}_g.graphml")
        print(f"Loaded graph from {folderpath}_g.graphml.")
        with open(f'{folderpath}_stat.json') as f:
            ground_truth_stat = json.load(f)
        print(f"Loaded graph stats from {folderpath}_stat.json.")
        with open(f'{folderpath}_motifs.json') as f:
            ground_truth_motifs = json.load(f)
        print(f"Loaded graph motif counts from {folderpath}_motifs.json.")
        return ground_truth_graph, ground_truth_stat, ground_truth_motifs

def load_experiment_results(folderpath):

    df_stats = pd.read_csv(f"{folderpath}/random_properties.csv")
    df_motifs = pd.read_csv(f"{folderpath}/random_motifs.csv")

    return df_stats, df_motifs

def combine_experiments(df_list, label_list):
    updated_df_list = []
    for df, label in zip(df_list, label_list):
        df = df.copy()
        df["condition"] = label
        updated_df_list.append(df)
    return pd.concat(updated_df_list, ignore_index=True)

def get_best_indices(df_combined, label_list):
    idx_list = []
    for label in label_list:
        subset = df_combined[df_combined["condition"] == label]
        best_row_idx = subset["energies"].idxmin()
        best_graph_id = df_combined.loc[best_row_idx, "graph_id"]
        idx_list.append(best_graph_id)
    return idx_list


def compute_errors(ground_truth_combined, df_combined_features):
    """
    Computes signed errors for each metric and the total aggregated energy.
    """
    detailed_losses = []
    total_energies = []

    for _, row in df_combined_features.iterrows():
        # current_values: extract only keys that exist in our target ground truth
        current_values = {k: row[k] for k in ground_truth_combined.keys() if k in row.index}
        
        # Use the corrected energy_delta logic
        energy, contributions = energy_delta(
            current_values, 
            ground_truth_combined, 
            return_details=True
        )
        
        detailed_losses.append(contributions)
        total_energies.append(energy)

    df_loss = pd.DataFrame(detailed_losses)
    df_loss["loss_sum"] = total_energies
    return df_loss

def compute_relative_error(df, target_dict):
    df_errors = pd.DataFrame(index=df.index)
    df_tmp = df.drop('graph_id', axis=1)
    
    for col in df_tmp.columns:
            df_errors[col] = (df[col] - target_dict[col]) / (target_dict[col] + df[col])

    df_errors["total_error"] = df_errors.abs().sum(axis=1)
    df_errors['graph_id'] = df['graph_id'].values

    return df_errors

def get_best_index(df_errors):
    
    closest_to_zero = df_errors["total_error"].abs().idxmin()
    best_graph_id = df_errors.loc[closest_to_zero, "graph_id"]
    
    return best_graph_id

def get_best_indices(df, n_top=5, criteria="total_error"):
    smallest_list_norm = list(
        df[criteria]
        .abs()
        .nsmallest(n_top)
        .index
        )
    
    return smallest_list_norm